- hosts: all
  become: yes
  tasks:
    - name: create the user
      user: name="{{ user }}" state=present createhome=yes shell=/bin/bash

    - name: allow user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '"{{ user }}" ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the sammy user
      authorized_key: user="{{ user }}" key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub