- hosts: master
  become: yes
  tasks:
    - name: reset the cluster
      shell: kubeadm reset -f
      args:
        chdir: $HOME
    - name: stop docker
      shell: systemctl stop docker
    - name: copy docker.service to set cgroup to systemd
      copy:
        src: docker.service
        dest: /usr/lib/systemd/system/docker.service
        remote_src: no
        owner: root
    - name: remove /etc/docker/daemon.json
      ansible.builtin.file:
        path: etc/docker/daemon.json
        state: absent
    - name: reload all deamons
      shell: systemctl daemon-reload
    - name: restart docker
      shell: systemctl restart docker
    - name: Remove file ca.crt
      ansible.builtin.file:
        path: /etc/kubernetes/pki/ca.crt
        state: absent
    - name: Remove file kubelet.conf
      ansible.builtin.file:
        path: /etc/kubernetes/kubelet.conf
        state: absent
    - name: turn swop off
      shell: swapoff -a

    - name: initialize the cluster
      shell: kubeadm init
      args:
        chdir: $HOME

    - name: create .kube directory
      become: yes
      become_user: "{{ user }}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: check if /etc/kubernetes/admin.conf exists
      stat: path=/etc/kubernetes/admin.conf
      register: file

    - name: copy admin.conf to user's kube config, if it exists
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ user }}/.kube/config
        remote_src: yes
        owner: "{{ user }}"
      when: file.stat.exists

    - name: copy weave.yml from controll to host
      copy:
        src: weave.yml
        dest: /home/{{ user }}/.kube/weave.yml
        remote_src: no
        owner: "{{ user }}"

    - name: install Pod network weave
      become: yes
      become_user: "{{ user }}"
      shell: kubectl apply -f /home/{{ user }}/.kube/weave.yml
      args:
        chdir: $HOME

    - name: check if /etc/kubernetes/admin.conf exists
      stat: path=/etc/kubernetes/admin.conf
      register: file

#    - name: ensure custom facts directory exists
#      file: >
#        path="{{ installdir }}"/../../"{{ configdir }}"
#        recurse=yes
#        state=directory
    - name: copy k8s admin.conf to controller computer, if it exists
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ configdir }}"
        remote_src: yes
        owner: "{{ user }}"
      when: file.stat.exists

    - name: set env variable
      shell: export KUBECONFIG="{{ configdir }}"/etc/kubernetes/admin.conf
