- hosts: master
  become: yes
  tasks:
    - name: reset the cluster
      shell: kubeadm reset -f
      args:
        chdir: $HOME
    - name: Remove file ca.crt
      ansible.builtin.file:
        path: /etc/kubernetes/pki/ca.crt
        state: absent
    - name: Remove file kubelet.conf
      ansible.builtin.file:
        path: /etc/kubernetes/kubelet.conf
        state: absent
    - name: turn swop off
      shell: swapoff -a

    - name: initialize the cluster
      shell: kubeadm init
      args:
        chdir: $HOME

    - name: create .kube directory
      become: yes
      become_user: sammy
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: check if /etc/kubernetes/admin.conf exists
      stat: path=/etc/kubernetes/admin.conf
      register: file

    - name: copy admin.conf to user's kube config, if it exists
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/jwewer/.kube/config
        remote_src: yes
        owner: jwewer
      when: file.stat.exists

#    - name: install Pod network weave
#      become: yes
#      become_user: sammy
#      shell: kubectl apply -f "https://cloud.weave.works/k8s/v1.16/net.yaml"
#      args:
#        chdir: $HOME

    - name: check if /etc/kubernetes/admin.conf exists
      stat: path=/etc/kubernetes/admin.conf
      register: file

    - name: copy k8s admin.conf to controller computer
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/Administrator/.kube/
      when: file.stat.exists

