- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: reset the cluster
      shell: kubeadm reset -f
      args:
        chdir: $HOME
    - name: stop docker
      shell: systemctl stop docker
    - name: copy docker.service to set cgroup to systemd
      copy:
        src: docker.service
        dest: /usr/lib/systemd/system/docker.service
        remote_src: no
        owner: root
    - name: remove /etc/docker/daemon.json
      ansible.builtin.file:
        path: etc/docker/daemon.json
        state: absent
    - name: reload all deamons
      shell: systemctl daemon-reload
    - name: restart docker
      shell: systemctl restart docker
    - name: Remove file ca.crt
      ansible.builtin.file:
        path: /etc/kubernetes/pki/ca.crt
        state: absent
    - name: Remove file kubelet.conf
      ansible.builtin.file:
        path: /etc/kubernetes/kubelet.conf
        state: absent
    - name: turn swop off
      shell: swapoff -a
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }}"
      args:
        chdir: $HOME
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
        PATH: /usr/sbin:/usr/local/bin:/usr/bin:/bin

