apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-50-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/minio/minio-volume-0/