apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-50-2
  labels:
    app: minio
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp/minio/minio-volume-2/
    server: 10.0.1.51
