apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-50-2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/minio-volume-2/