apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-50-3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /dev/sdb1/data/minio-volume-3/